# Generated by Django 3.0.7 on 2025-04-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_favorito'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pdfdata',
            name='dashboard_p_user_id_9fc8c2_idx',
        ),
        migrations.AddField(
            model_name='pdfdata',
            name='activity_type',
            field=models.CharField(choices=[('Game', 'Game'), ('Training', 'Training')], default='Game', max_length=20),
        ),
        migrations.AddField(
            model_name='pdfdata',
            name='session_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='pdfdata',
            index=models.Index(fields=['user', 'description', 'date', 'activity_type', 'session_number'], name='dashboard_p_user_id_7f1cca_idx'),
        ),
    ]
