# Generated by Django 3.0.7 on 2025-05-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_insert_pdfkeywords'),
        ('dashboard', '0008_pdfprocesslog'),
    ]

    operations = [
    ]
